In [4]:
import pandas as pd

df = pd.read_excel("HD_phaseGenes.xlsx", sheet_name="Table S2 - Phase C,D Gene Stats", header=26)
print(df.Phase.value_counts())
df

Phase
D     719
C+    327
C-    220
Name: count, dtype: int64

,Gene,Phase C p-value,Phase C effect,Phase C fold-change,Phase D p-value,Phase D effect,Pct cells,Phase,Highly expressed C+,Highly expressed C-,De-repressed phase D,Case-control p-value,Case-control fold-change
0,A1BG,0.506,-0.000587,0.916,0.0698,0.509211,13.69,NaN,N,N,N,0.005290,0.790
1,A1BG-AS1,0.967,0.000017,1.002,0.0967,0.225031,49.68,NaN,N,N,N,0.168000,0.927
2,A1CF,0.122,-0.002294,0.709,0.581,0.234565,7.53,NaN,N,N,N,0.002700,0.720
3,A2M,0.0,0.003404,1.666,0.185,0.303098,18.77,NaN,N,N,N,0.000690,0.504
4,A2M-AS1,0.00646,0.002407,1.435,0.495,0.224549,9.37,NaN,N,N,N,0.000036,1.512
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37726,hsa-mir-550a-2,NA,NA,NaN,NA,NA,0.00,NaN,N,N,N,0.222000,0.906
37727,snoR1,0.0374,-0.012096,0.163,0.0666,1.357486,1.41,NaN,N,N,N,0.539000,1.361
37728,snoU83B,NA,NA,NaN,NA,NA,0.00,NaN,N,N,N,0.106000,0.907
37729,snoZ196,NA,NA,NaN,NA,NA,0.06,NaN,N,N,N,0.302000,1.083
37730,snoZ278,NA,NA,NaN,NA,NA,0.00,NaN,N,N,N,0.362000,0.967

In [2]:
# phase D
phase_d = df[df["Phase"] == "D"]
display(phase_d[["Gene", "Phase D p-value", "Phase D effect", "Phase"]])
print(phase_d.Gene.to_list())

phase_d.to_csv("phase_d_genes.csv", index=False)

             Gene Phase D p-value Phase D effect Phase
51          ABCA8             0.0        7.37272     D
74          ABCC9             0.0       5.523023     D
560    AC005165.1             0.0       2.961955     D
1017   AC007091.1             0.0       6.530972     D
1308   AC008060.1             0.0       6.244598     D
...           ...             ...            ...   ...
37072        ZIC4             0.0       6.540266     D
37302      ZNF423             0.0       3.413034     D
37384      ZNF536             0.0       5.421753     D
37450      ZNF608             0.0         2.5012     D
37701      ZSCAN9             0.0        4.37378     D

[719 rows x 4 columns]

['ABCA8', 'ABCC9', 'AC005165.1', 'AC007091.1', 'AC008060.1', 'AC023886.1', 'AC027117.2', 'AC069120.1', 'AC069208.1', 'AC090502.1', 'AC090833.1', 'AC091940.1', 'AC092958.1', 'AC093330.2', 'AC093503.3', 'AC098829.1', 'AC104574.2', 'AC110023.1', 'AC110285.1', 'AC112206.2', 'AC243773.2', 'ACOT11', 'ACOT7', 'ACSBG1', 'ACSS1', 'ACTB', 'ACTG1', 'ADARB2', 'ADCY2', 'ADCY8', 'ADGRG1', 'ADRA1A', 'AEBP1', 'AHNAK', 'AL049874.3', 'AL136311.1', 'AL354809.1', 'AL359922.1', 'AL391807.1', 'AL445623.2', 'AL590094.1', 'AL590617.2', 'ALDH1A1', 'ALDH1L1', 'ALDOA', 'ALDOC', 'AMER2', 'AMOTL2', 'AMPD3', 'ANAPC11', 'ANGPT1', 'ANGPTL4', 'ANK1', 'ANKRD29', 'ANKRD44', 'ANO4', 'APOE', 'AQP1', 'ARHGAP23', 'ARHGAP24', 'ARHGAP42', 'ARHGEF40', 'ARL4C', 'ARL6IP1', 'ASPA', 'ATP1A2', 'ATP1B1', 'ATP2B4', 'ATP5D', 'ATP5E', 'ATP5H', 'ATP5I', 'ATP5J', 'ATP5J2', 'ATP5O', 'ATP6AP1', 'ATP6V0A1', 'ATP6V0B', 'ATP6V1F', 'ATP6V1G1', 'AURKAIP1', 'B2M', 'B4GAT1', 'BAG3', 'BANF1', 'BCAS1', 'BDH2', 'BEST1', 'BEX1', 'BEX3', 'BEX4', 'BMP7', 'BMPR1B', 'BTF3', 'BTG1', 'C10orf90', 'C12orf57', 'C14orf2', 'C14orf39', 'C19orf70', 'C1orf122', 'C1orf61', 'C1orf87', 'C3', 'C4orf22', 'C4orf48', 'CA2', 'CA8', 'CALCOCO2', 'CALM1', 'CALM2', 'CALR', 'CALY', 'CAMK2D', 'CAMK2N1', 'CARNS1', 'CBFB', 'CBR1', 'CBX8', 'CC2D2A', 'CCDC50', 'CCDC85B', 'CCT4', 'CD22', 'CD44', 'CD55', 'CD81', 'CD82', 'CDC42EP4', 'CDH13', 'CDH19', 'CDH20', 'CDK18', 'CDK2AP2', 'CDKN2A', 'CDKN2B', 'CDKN2B-AS1', 'CECR2', 'CERCAM', 'CFL2', 'CGNL1', 'CHCHD2', 'CHI3L1', 'CLDN11', 'CLDND1', 'CLMN', 'CLSPN', 'CLU', 'CNDP1', 'CNP', 'COBLL1', 'COL4A5', 'COLEC12', 'COPE', 'COPS9', 'COTL1', 'COX14', 'COX4I1', 'COX5B', 'COX6B1', 'COX6C', 'COX7A2', 'COX7B', 'COX7C', 'COX8A', 'CP', 'CPM', 'CRABP1', 'CREB5', 'CROCC', 'CRYAB', 'CSGALNACT1', 'CSRP1', 'CST3', 'CSTB', 'CTSD', 'CXXC5', 'CYBRD1', 'DAAM2', 'DCXR', 'DDR1', 'DDT', 'DNAH14', 'DNAJA1', 'DNAJB6', 'DOCK10', 'DOCK2', 'DOCK5', 'DPF3', 'DPYSL2', 'DRAP1', 'DUSP10', 'DYNLL1', 'ECH1', 'EDF1', 'EEF1A1', 'EEF1B2', 'EEF1D', 'EEF2', 'EFEMP1', 'EFHD1', 'EID1', 'EIF1', 'ELAVL2', 'ELOB', 'EMC10', 'EMX2OS', 'ENAH', 'ENO2', 'ENPP2', 'EPHX1', 'ERBB3', 'ERBIN', 'ETS1', 'EZR', 'FA2H', 'FAM107A', 'FAM107B', 'FAM189A2', 'FAM69C', 'FAU', 'FBXL7', 'FCHSD2', 'FERMT2', 'FGF1', 'FGFR1', 'FGFR2', 'FGFR3', 'FIGN', 'FIS1', 'FKBP2', 'FLJ12825', 'FOLH1', 'FOS', 'FOXD1', 'FRMPD2', 'FTH1', 'FTL', 'GAB1', 'GABARAP', 'GABARAPL2', 'GABRG1', 'GADD45B', 'GADD45GIP1', 'GALNT9', 'GAPDH', 'GDI1', 'GFAP', 'GLI2', 'GLIPR2', 'GLIS3', 'GLUL', 'GNAS', 'GNG2', 'GPRC5B', 'GPS2', 'GPX1', 'GPX4', 'GRAMD3', 'GREM1', 'GRIA4', 'GSN', 'GTF3C6', 'GUK1', 'H1FX', 'H2AFZ', 'H3F3B', 'HAND2-AS1', 'HEPACAM', 'HHIP', 'HIF3A', 'HINT1', 'HIP1R', 'HIPK2', 'HLA-A', 'HLA-C', 'HNRNPM', 'HOTAIRM1', 'HOXA-AS2', 'HOXA-AS3', 'HOXA13', 'HOXB-AS1', 'HOXB-AS3', 'HOXC10', 'HOXC4', 'HOXD-AS2', 'HOXD11', 'HPN-AS1', 'HPSE2', 'HSD17B11', 'HSP90AA1', 'HSP90AB1', 'HSPA1A', 'HSPA1B', 'HSPA5', 'HSPA8', 'HSPB1', 'HSPE1', 'IDS', 'IFITM3', 'IL13RA1', 'IP6K3', 'IRX5', 'ISCU', 'ITGA2', 'ITGA6', 'ITGB4', 'ITGB5', 'ITM2B', 'ITM2C', 'ITPKB', 'ITPR2', 'JSRP1', 'JUN', 'KANK1', 'KCNC2', 'KCNH8', 'KCNJ10', 'KCNJ3', 'KIAA1211', 'KIAA1755', 'KIF2A', 'KIRREL', 'KLF12', 'KLF15', 'LAMA2', 'LAMP2', 'LAMTOR4', 'LBX1-AS1', 'LDHB', 'LHFP', 'LHX1', 'LHX5', 'LHX5-AS1', 'LHX6', 'LHX9', 'LINC00320', 'LINC00499', 'LINC00639', 'LINC00682', 'LINC01138', 'LINC01170', 'LINC01608', 'LINC01792', 'LINC01977', 'LINC02381', 'LITAF', 'LPAR1', 'LRIG1', 'LRP10', 'LRP2', 'LRP2BP', 'LRP4', 'LRRC63', 'LTBP1', 'LUC7L3', 'MAGED2', 'MAL', 'MAML2', 'MAP4K4', 'MAPKAPK2', 'MAPT', 'MARCKS', 'MBP', 'MIR219A2', 'MLC1', 'MOBP', 'MOG', 'MRFAP1', 'MRPL20', 'MRVI1', 'MSC-AS1', 'MT-CO2', 'MT2A', 'MT3', 'MTCH1', 'MUM1', 'MYL6', 'MYO10', 'MYO1E', 'MYRF', 'MZT2B', 'NAB1', 'NACA', 'NACC2', 'NCKAP5', 'NCOR1', 'NDE1', 'NDRG1', 'NDRG2', 'NDUFA1', 'NDUFA2', 'NDUFA3', 'NDUFA4', 'NDUFAF3', 'NDUFB10', 'NDUFB7', 'NDUFB8', 'NDUFC1', 'NDUFS5', 'NEAT1', 'NEDD8', 'NENF', 'NEUROD2', 'NFIB', 'NFIX', 'NFKBIA', 'NGB', 'NINJ2', 'NKX2-5', 'NPY', 'NR2F1-AS1', 'NR4A2', 'NRN1', 'NUDC', 'NXPH1', 'OAF', 'OAZ1', 'ONECUT1', 'OPALIN', 'OST4', 'PADI2', 'PALM2', 'PANCR', 'PARP14', 'PARP8', 'PBXIP1', 'PCBP1', 'PCDH15', 'PCSK1N', 'PDE1A', 'PDZRN3', 'PEA15', 'PEBP1', 'PEX5L', 'PFDN5', 'PFKP', 'PFN1', 'PHLDB1', 'PHPT1', 'PHYHIPL', 'PIEZO2', 'PITX1', 'PLA2G16', 'PLA2G4A', 'PLCB4', 'PLEKHG1', 'PLEKHH1', 'PLOD2', 'PLP1', 'PLPP3', 'PLS3', 'PLSCR4', 'PLXNB1', 'PMP22', 'POLR2F', 'POLR2I', 'POLR2J', 'POLR2L', 'POU4F1', 'POU4F2', 'PPDPF', 'PPFIBP2', 'PPP3CB-AS1', 'PRDM13', 'PRDM16', 'PRDX1', 'PRDX2', 'PRDX5', 'PRELID1', 'PREX1', 'PREX2', 'PRKCA', 'PRNP', 'PROX1', 'PRR5L', 'PRUNE2', 'PSENEN', 'PSMA7', 'PSMC5', 'PTMA', 'PTPRC', 'PTPRK', 'PTPRZ1', 'QKI', 'RABAC1', 'RAC1', 'RACK1', 'RANBP3L', 'RASA3', 'RASGRP3', 'RASL12', 'RASSF2', 'RASSF4', 'RFTN2', 'RGCC', 'RGMA', 'RHBDD2', 'RHOB', 'RHOU', 'RN7SL2', 'RNF219-AS1', 'RNF220', 'RPL10', 'RPL10A', 'RPL11', 'RPL12', 'RPL13', 'RPL13A', 'RPL14', 'RPL15', 'RPL18', 'RPL18A', 'RPL19', 'RPL21', 'RPL22', 'RPL23A', 'RPL24', 'RPL26', 'RPL27', 'RPL28', 'RPL29', 'RPL3', 'RPL30', 'RPL32', 'RPL34', 'RPL35', 'RPL35A', 'RPL36', 'RPL36AL', 'RPL38', 'RPL39', 'RPL4', 'RPL41', 'RPL5', 'RPL6', 'RPL7', 'RPL7A', 'RPL8', 'RPL9', 'RPLP0', 'RPLP1', 'RPLP2', 'RPS11', 'RPS12', 'RPS13', 'RPS14', 'RPS15', 'RPS15A', 'RPS16', 'RPS17', 'RPS18', 'RPS19', 'RPS19BP1', 'RPS2', 'RPS21', 'RPS23', 'RPS24', 'RPS25', 'RPS26', 'RPS27', 'RPS27A', 'RPS28', 'RPS29', 'RPS3', 'RPS3A', 'RPS4X', 'RPS5', 'RPS6', 'RPS7', 'RPS8', 'RPS9', 'RPSA', 'RRBP1', 'RTL8C', 'SAMD4A', 'SAP18', 'SARAF', 'SBDS', 'SCAND1', 'SCD', 'SDC4', 'SDF4', 'SEC11C', 'SEC62', 'SELENOM', 'SELENOP', 'SELENOW', 'SEMA3B', 'SEPT10', 'SEPT7', 'SERF2', 'SERINC1', 'SFTA3', 'SH3BGRL3', 'SH3TC2', 'SHOX2', 'SHROOM4', 'SIX1', 'SKAP2', 'SLC14A1', 'SLC17A6', 'SLC17A7', 'SLC1A2', 'SLC1A3', 'SLC25A18', 'SLC25A5', 'SLC26A3', 'SLC39A12', 'SLC6A5', 'SLC7A11', 'SLCO1A2', 'SLCO1C1', 'SMIM26', 'SMIM29', 'SNHG6', 'SNRNP70', 'SNRPD2', 'SNTB1', 'SOD1', 'SORT1', 'SOX2', 'SOX5', 'SOX6', 'SOX9', 'SP100', 'SPAG6', 'SPP1', 'SRCIN1', 'SREBF1', 'SREBF2', 'SRP14', 'SSR4', 'SST', 'ST18', 'STAT5A', 'STK3', 'STMN1', 'STRAP', 'STRIP1', 'STUB1', 'SURF1', 'SVEP1', 'SYNJ2', 'SYNPO2', 'SYT17', 'SYTL4', 'TAL1', 'TBKBP1', 'TBR1', 'TBX5', 'TCEAL4', 'TCEAL6', 'TCEAL9', 'TCF25', 'TCF4', 'TCP11L2', 'TFAP2D', 'TGFBR2', 'TIMP2', 'TLE2', 'TLE3', 'TMA7', 'TMBIM6', 'TMEM108', 'TMEM130', 'TMEM144', 'TMEM160', 'TMEM165', 'TMEM235', 'TMEM258', 'TMEM41B', 'TMEM63A', 'TMEM98', 'TMSB10', 'TMSB4X', 'TMTC2', 'TNS1', 'TOMM20', 'TOX', 'TPI1', 'TRIM2', 'TRMT112', 'TSC22D4', 'TSPYL1', 'TSPYL2', 'TTLL7', 'TTYH2', 'TUBA1A', 'TUBA1B', 'TUBB2A', 'TUBB4B', 'TWIST1', 'UBA52', 'UBB', 'UBC', 'UBL5', 'UCHL1', 'UGT8', 'UQCR10', 'UQCRQ', 'USMG5', 'USP54', 'VAMP2', 'VCAN', 'VEGFB', 'VRK2', 'WBP2', 'WDR83OS', 'YPEL3', 'ZBTB16', 'ZC3HAV1', 'ZFP36L1', 'ZIC1', 'ZIC4', 'ZNF423', 'ZNF536', 'ZNF608', 'ZSCAN9']

In [6]:
# phase c+
phase_c = df[df["Phase"] == "C+"]
display(phase_c[["Gene", "Phase C p-value", "Phase C effect", "Phase"]])
print(phase_c.Gene.to_list())

phase_c.to_csv("phase_c_plus_genes.csv", index=False)

             Gene Phase C p-value Phase C effect Phase
22           AAK1             0.0       0.000716    C+
322    AC004158.1             0.0       0.002635    C+
552    AC005154.1             0.0       0.001395    C+
683    AC005562.1             0.0       0.001377    C+
2101   AC010615.4             0.0       0.001315    C+
...           ...             ...            ...   ...
37350      ZNF493             0.0       0.001048    C+
37377      ZNF528             0.0       0.001227    C+
37451      ZNF609             0.0       0.000976    C+
37473      ZNF638             0.0       0.000802    C+
37622      ZNF831             0.0       0.001673    C+

[327 rows x 4 columns]

['AAK1', 'AC004158.1', 'AC005154.1', 'AC005562.1', 'AC010615.4', 'AC024901.1', 'AC026790.1', 'AC034226.1', 'AC093890.1', 'AC097515.1', 'AC104090.1', 'ACVR2A', 'ADAM22', 'ADD3', 'ADGRL2', 'AEBP2', 'AFDN', 'AGTPBP1', 'AKAP13', 'AKAP6', 'AKT3', 'AL359710.1', 'AL589740.1', 'ANK2', 'ANK3', 'ANKH', 'ANKIB1', 'ANKRD17', 'APTX', 'ARFGEF1', 'ARFGEF3', 'ARHGAP26', 'ARHGEF12', 'ARHGEF26-AS1', 'ARID4A', 'ARID4B', 'ARIH1', 'ASTN1', 'ATE1', 'ATP1A3', 'ATP2A3', 'ATP8A2', 'ATP9B', 'ATR', 'ATRX', 'BASP1', 'BDP1', 'BICD1', 'BICDL1', 'BMPR2', 'BRAF', 'BRD1', 'C5orf42', 'CACNA1C', 'CACNA1D', 'CADM2', 'CADPS', 'CAMSAP2', 'CAPN7', 'CAPS2', 'CASC15', 'CCDC192', 'CCPG1', 'CCSER1', 'CDC42BPA', 'CDK13', 'CHGA', 'CHL1', 'CHM', 'CHORDC1', 'CLASP2', 'CNOT4', 'CNOT6L', 'CNTN1', 'CNTNAP2', 'CSMD3', 'CSRNP3', 'CUL1', 'CYP4X1', 'DCDC2C', 'DDX5', 'DENND4A', 'DLEU2', 'DLG2', 'DMTF1', 'DNAJC6', 'DNM1L', 'DOPEY1', 'DSCAM', 'DYNC1I1', 'DYNC1I2', 'DYRK1A', 'EIF4G3', 'EPDR1', 'ERC1', 'ERICH3', 'EXOC4', 'FAF1', 'FAM153B', 'FAM153C', 'FAM155A', 'FAM169A', 'FAM196B', 'FBXO21', 'FBXW7', 'FGF12', 'FOCAD', 'FRMD4A', 'FTX', 'FXR1', 'GABRA2', 'GABRG3', 'GALNT11', 'GDAP1', 'GDNF-AS1', 'GLS', 'GPATCH2', 'GPATCH8', 'GPHN', 'GPM6A', 'GPR149', 'GRIA1', 'GSTA4', 'GTF2A1', 'HGSNAT', 'HLTF', 'HMBOX1', 'HMGN1', 'HNRNPA2B1', 'HNRNPD', 'HSPA12A', 'ILDR2', 'INPP4B', 'INTS6', 'INTU', 'JAKMIP2', 'JPX', 'KANSL1', 'KDM5A', 'KIAA0825', 'KIAA1109', 'KIDINS220', 'KIF21A', 'KIF3A', 'KIFAP3', 'KIZ', 'KMT2C', 'KMT2E', 'KSR2', 'LCLAT1', 'LINC00632', 'LINC00882', 'LINC00886', 'LINC01006', 'LINC01105', 'LINC01135', 'LINC01184', 'LINC01376', 'LINC01473', 'LINC02062', 'LINC02223', 'LRP1B', 'LRRC4C', 'LRRTM4', 'LSM14A', 'MAGI2', 'MAGI2-AS3', 'MAMDC2', 'MAMDC2-AS1', 'MAP2', 'MAP7', 'MAPK10', 'MAPK8', 'MARK1', 'MAST1', 'MATR3', 'MBD5', 'MCF2L2', 'MED27', 'MEF2C-AS1', 'MEF2C-AS2', 'MICU1', 'MICU3', 'MIR100HG', 'MIR124-2HG', 'MIR137HG', 'MIR99AHG', 'MLLT10', 'MON2', 'MPP7', 'MPPED2', 'MYCBP2', 'N4BP2L2', 'NAALAD2', 'NALCN', 'NAPB', 'NBAS', 'NCOA1', 'NDFIP1', 'NDFIP2', 'NEK10', 'NIPAL2', 'NIPBL', 'NOL4', 'NORAD', 'NRF1', 'NRG1', 'NRXN3', 'NSD3', 'NUP58', 'PAPOLA', 'PBRM1', 'PCNX1', 'PCNX2', 'PDZRN4', 'PGAP1', 'PHC3', 'PHF3', 'PHTF1', 'PIAS1', 'POLR2A', 'PPA2', 'PPM1B', 'PPP1R12B', 'PPP4R4', 'PRKCI', 'PSIP1', 'PSPC1', 'PTPRD', 'PUS7L', 'PWAR1', 'PWAR5', 'PWAR6', 'RAB11A', 'RAB3C', 'RBM5', 'REPS1', 'REV3L', 'RFWD2', 'RICTOR', 'RIMS2', 'RIT2', 'ROBO1', 'RTN3', 'SCN2A', 'SERGEF', 'SETD2', 'SEZ6L', 'SGCZ', 'SGSM1', 'SHANK2', 'SLC22A25', 'SLC36A1', 'SLC38A6', 'SLC4A10', 'SMC5-AS1', 'SNHG14', 'SNTG1', 'SON', 'SPECC1', 'SPIN1', 'SRGAP3', 'SRPK2', 'SRRM2', 'ST3GAL5', 'STAU2', 'STOX2', 'STRN3', 'STXBP5', 'SUPT3H', 'SV2B', 'SYBU', 'TAPT1-AS1', 'TARBP1', 'TBC1D5', 'TBCK', 'TENM4', 'THOC1', 'TIA1', 'TIAM2', 'TMEM232', 'TNRC6A', 'TNRC6C', 'TP53BP1', 'TRA2A', 'TRIP12', 'TRPC1', 'TTC3', 'TTC39C', 'TTC8', 'UBE2E2', 'UBN2', 'UBQLN1', 'UBR2', 'UBR3', 'UBR5', 'UBXN4', 'UNC79', 'UPP2', 'USP24', 'USP34', 'USP47', 'UTY', 'VEZT', 'VPS13B', 'VPS13C', 'VWDE', 'WDFY2', 'WDR78', 'WNK1', 'WNK2', 'XIST', 'XPR1', 'YWHAG', 'ZBTB20', 'ZCCHC17', 'ZDHHC20', 'ZDHHC21', 'ZEB1', 'ZFAND3', 'ZMYM2', 'ZMYM4', 'ZNF493', 'ZNF528', 'ZNF609', 'ZNF638', 'ZNF831']

In [7]:
# phase c-
phase_c = df[df["Phase"] == "C-"]
display(phase_c[["Gene", "Phase C p-value", "Phase C effect", "Phase"]])
print(phase_c.Gene.to_list())

phase_c.to_csv("phase_c_minus_genes.csv", index=False)

             Gene Phase C p-value Phase C effect Phase
40           ABAT             0.0      -0.001111    C-
1445   AC008591.1             0.0      -0.001579    C-
4515   AC069437.1             0.0      -0.001738    C-
4860   AC079385.1             0.0      -0.002295    C-
5229   AC090124.1             0.0      -0.005723    C-
...           ...             ...            ...   ...
36722       YPEL1             0.0      -0.002457    C-
37088       ZMAT4             0.0      -0.001203    C-
37620       ZNF83             0.0      -0.003241    C-
37661       ZNRF3             0.0      -0.001219    C-
37707      ZSWIM6             0.0      -0.001151    C-

[220 rows x 4 columns]

['ABAT', 'AC008591.1', 'AC069437.1', 'AC079385.1', 'AC090124.1', 'AC090124.2', 'AC092422.1', 'AC092546.1', 'AC093523.1', 'AC109466.1', 'AC127164.1', 'ACTN1', 'ADAM12', 'ADAMTS19', 'ADAMTS3', 'ADAMTSL1', 'ADCY5', 'AKAP5', 'AL020994.3', 'AL049830.3', 'AL355472.3', 'AL355472.4', 'ANKRD18A', 'ANKS1B', 'ANO3', 'AP1G2', 'AQP4-AS1', 'ARAP2', 'ARMC9', 'ARNT2', 'ARPP19', 'ARPP21', 'ATP2B1', 'ATP2B2', 'B3GLCT', 'BBS2', 'BCL11B', 'C6orf141', 'CA12', 'CACNA1E', 'CACNA2D3', 'CACNB2', 'CAMK2B', 'CAMK4', 'CAMKK2', 'CARHSP1', 'CATSPERG', 'CCDC88C', 'CDC40', 'CDH11', 'CDKL5', 'CELF2', 'CHST11', 'CHST15', 'CHSY3', 'CIT', 'CKB', 'CNR1', 'COA6', 'COCH', 'CORO2B', 'CRYBG3', 'CTTNBP2', 'CYP46A1', 'DAPK1', 'DDO', 'DGKB', 'DGKH', 'DGKI', 'DKK3', 'DLGAP1', 'DNMT3A', 'DOCK4', 'DPY19L3', 'DPYSL5', 'DRD1', 'EGFR', 'EML1', 'EPB41L2', 'EPHX4', 'EYA1', 'FAM171A1', 'FAT3', 'FBXW8', 'FOXG1', 'FSTL4', 'FTCD', 'GALNT18', 'GNAL', 'GNG7', 'GPC5', 'GPR137C', 'GRIA3', 'GRM3', 'GRM8', 'GUCY1A2', 'HMP19', 'HRH2', 'HS3ST5', 'HTR2C', 'HTR4', 'INPP5A', 'IVNS1ABP', 'JAKMIP1', 'JPH4', 'KAZN', 'KCNA4', 'KCNAB1', 'KCND2', 'KCNH1', 'KCNIP2-AS1', 'KCNK1', 'KCNQ5', 'KCTD1', 'KIAA1211L', 'KIAA1462', 'LAMP5', 'LARGE1', 'LDB2', 'LDLRAD4', 'LINC00894', 'LINC01085', 'LINC01250', 'LINC01551', 'LINC02137', 'LPL', 'LRRTM3', 'MACROD2', 'MALAT1', 'MAN1A1', 'MAN2B2', 'MAPK4', 'MBNL2', 'MEIS2', 'MERTK', 'MME', 'MOB3B', 'MTHFD1', 'NDST3', 'NETO2', 'NFATC2', 'NGEF', 'NPAS2', 'ONECUT2', 'OSBPL8', 'PASK', 'PCP4', 'PDE10A', 'PDE1B', 'PDIA6', 'PDZD2', 'PHACTR1', 'PITPNC1', 'PITPNM2', 'PLCB1', 'PLEKHA5', 'PLK2', 'PPP1R16B', 'PPP1R1B', 'PPP2R2B', 'PPP3CA', 'PRKCB', 'PRKCH', 'PRMT8', 'PSD3', 'PTPN5', 'PTPRT', 'RAP1GAP', 'RAPGEF5', 'RARB', 'RASD2', 'RERG', 'RFX4', 'RGS20', 'RGS4', 'RGS9', 'RHOBTB2', 'RIC8B', 'RNF144A', 'RPL37A', 'RYR2', 'RYR3', 'SCARB1', 'SH3RF2', 'SIK3', 'SLC24A2', 'SLC35F3', 'SLC47A1', 'SLC9A7', 'SNAP25', 'SNTB2', 'SORBS1', 'SOX9-AS1', 'SPOCK1', 'STARD4', 'STRIP2', 'STRN', 'STXBP5L', 'SV2C', 'SYNDIG1L', 'TAC1', 'TANC2', 'TCAF1', 'TESC', 'TESPA1', 'THSD4', 'TJP1', 'TLE4', 'TMOD1', 'TOMM70', 'TPT1', 'VAV3', 'WASF1', 'WFS1', 'WIPF3', 'YPEL1', 'ZMAT4', 'ZNF83', 'ZNRF3', 'ZSWIM6']